#!/usr/bin/env ruby

# bud: brew-update descriptions
#
# With the output of `brew update` in the paste buffer, this will list the
# descriptions of the uninstalled formulae.

require 'colorize'

# Given an array of arrays representing successive rows of a table, return a
# pivoted version of the table, with the original's columns turned into rows.

def pivot(table)
  max_length = table.reduce(0) do |max, row|
    ((current = row.length) > max) ? current : max
  end

  pivoted = []
  for i in 0..(max_length - 1)
    pivoted << table.map { |row| row[i] }.compact
  end

  pivoted
end

# Given an array of lines and a regex containing "left" and "right" tags,
# return:
#
# 1. An array of two-element arrays, representing the lines split on the
#    regular expression.
# 2. The length of the longest left-hand component.

def split(lines, regex)
  pieces = []
  offset = 0
  lines.each do |line|
    matches = regex.match(line)
    pieces << [matches[:left], matches[:right]]
    offset = [offset, matches[:left].length].max
  end
  [pieces, offset]
end


def present(pieces, offset, splitter)
  pieces.each do |piece|
    padding = ' ' * (offset - piece.first.length)
    print(
      padding,
      piece.first.colorize(:blue),
      splitter,
      piece.last,
      "\n"
    )
  end
end

# ------------------

# Names are separated by either AT LEAST two spaces, or a newline.
name_splitter = /\s{2,}|\n/

# Installed packages have their name-strings end with " (installed)".
installed = / \(installed\)$/

desc_splitter = ':'
desc_regex = /(?<left>.*?)#{desc_splitter}(?<right>.*)/

# Action!

input = %x(pbpaste).split("\n").inject([]) do |acc, line|
  acc << line.split(name_splitter)
end

flattened = pivot(input).flatten
filtered = flattened.reject { |update| installed.match(update) }

descriptions = %x(brew desc #{filtered.join(' ')}).split("\n")

pieces, offset = split(descriptions, desc_regex)
present(pieces, offset, desc_splitter)
