#!/usr/bin/env bash

if [ -z "${@}" ]; then
  target="."
else
  target="${@}"
fi

echo -n "Really purge \"${target}\"? "

read answer

if [[ $answer =~ [Yy] ]]; then
  git reset -q HEAD ${target}
  git checkout -- ${target}
  git clean -fd ${target}
else
  echo "Bailing."
fi
