#!/usr/bin/env ruby -w

# Stash the homebrew formulae and gems installed on a given host to a
# Dropbox file.

# (File under "hack and a half", but serves its purpose.)

require 'Date'
require 'FileUtils'

class Stasher

  def initialize
    @names   = {
      "brew" => "brew",
      "gem"  => "gems"
    }

    @stash_path = File.expand_path("~/Dropbox/Resources/modulist")
    FileUtils.mkdir_p(@stash_path)
  end

  def full_paths(type)
    hostname = %x(hostname -s).chomp

    base = [hostname, type].join('_')

    [
      File.join(@stash_path, "#{base}.prev.txt"),
      File.join(@stash_path, "#{base}.txt")
    ]
  end

  def log(type)
    old, latest = full_paths(@names[type])

    FileUtils.mv(latest, old) if File.exist?(latest)

    items = %x(#{type} list)
    puts "#{@names[type]}: #{items.split.count}"
    File.open(latest, "w") do |handle|
      handle.write(items)
    end

    FileUtils.rm(old) if File.exist?(old)

  end

end

stash = Stasher.new

types = %w[brew gem]

types.each do |type|
  stash.log(type)
end
