#!/usr/bin/env ruby

require 'pp'
require 'colorize'
# require 'term/ansicolor'

splitter = ARGV.shift
myregex = /(?<left>.*?)#{splitter}(?<right>.*)/

lines = ARGF.readlines.map(&:chomp)


pieces = []
offset = 0
lines.each do |line|
  matches = myregex.match(line)
  pieces << [matches[:left], matches[:right]]
  offset = [offset, matches[:left].length].max
end


pieces.each do |piece|
  padding = ' ' * (offset - piece.first.length)
  print(
    padding,
    piece.first.colorize(:blue),
    splitter,
    piece.last,
    "\n"
  )
end
